databases:
  - name: pomodoro-db
    plan: free

services:
  - type: web
    name: pomodoro
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pomodoro-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
